version: '3.3'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    container_name: backend
    env_file: .env
    ports:
      - 5000:5000
    depends_on:
      - postgres
    command: sh -c "node dist/main.js"
    restart: unless-stopped

  bot:
    build:
      context: ./
      dockerfile: Dockerfile.bot
    container_name: bot
    env_file: .env
    restart: unless-stopped

  frontend:
    image: nginx
    container_name: frontend
    ports:
      - 4201:80
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist/apps/frontend:/usr/share/nginx/html
    restart: unless-stopped

  admin:
    image: nginx
    container_name: admin
    ports:
      - 4200:80
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist/apps/admin:/usr/share/nginx/html
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: 'postgres:15'
    env_file: .env.db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  postgres:
